name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Heap Test
      id: heap-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Heap Test
        setup-command: make clean
        command: make testHeap
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HEAP-TEST_RESULTS: "${{steps.heap-test.outputs.result}}"
      with:
        runners: heap-test
